### ISSUE TITLE
Support python-3.12

### ISSUE THREAD

**Issue by vmiklos** [mautrix/signal#381]
It seems that e.g. on Fedora 39 (that comes with python-3.12) the

```
pip3 install mautrix-signal
```

command fails:

```
Collecting mautrix-signal
...
      creating build/temp.linux-x86_64-cpython-312/asyncpg/pgproto
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -I/usr/include/python3.12 -c asyncpg/pgproto/pgproto.c -o build/temp.linux-x86_64-cpython-312/asyncpg/pgproto/pgproto.o -O2 -fsigned-char -Wall -Wsign-compare -Wconversion
...

      asyncpg/pgproto/pgproto.c: In function ‘__Pyx_PyIndex_AsSsize_t’:
      asyncpg/pgproto/pgproto.c:43487:45: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
      43487 |     const digit* digits = ((PyLongObject*)b)->ob_digit;
            |                                             ^~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for asyncpg
Failed to build asyncpg
ERROR: Could not build wheels for asyncpg, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
```

The workaround for now seems to be to clone the repo, manually delete the asyncpg dependency, install the dependencies and then install this repo using --no-deps. That is acceptable for me, since I use sqlite, but it's far from ideal. :-)

I imagine the solution would be to depend on a newer asyncpg, asyncpg-0.29.0 works fine with python-3.12, but I'm not sure if there are other problems with it. Thanks.

Full log: [log.txt](https://github.com/mautrix/signal/files/13620795/log.txt)

**Comment by tulir** [comment]
Nothing checks dependencies at runtime so you can also just update asyncpg manually. Won't be fixed other than that at this stage

**Comment by vmiklos** [comment]
I see, thanks, that's a better workaround. :-)

**Comment by emdete** [comment]
mautrix-signal pins asyncpg to <0.28,>=0.20 which can't be build with 3.12, why is it pinned at all? is there a good reason?

**Comment by kpfleming** [comment]
The bridge has been rewritten in Go, the Python version is really not usable at this point.
